name: ArchonCore
main: main.java.Archon.Main
version: "alpha-1.4.1"
api: ["1.2"]
load: POSTWORLD
author: ArchonKlaus
description: ArchonCore
website: ArchonTeam.org

commands:
  fly:
    description: ArchonCore Fly Command
    permission: archon.fly
